document default LEAD columns
fivetran/dbt_marketo pull request #32
Opened 2024-02-29 15:52 UTC by fivetran-jamie

## PR Overview
**This PR will address the following Issue/Feature:**
https://github.com/fivetran/dbt_marketo_source/pull/35

**This PR will result in the following new package version:**

v0.11.0 -- we are aliasing fields that existed but were not aliased before

**Please detail what change(s) this PR introduces and any additional information that should be known during the review of this PR:**

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [x] dbt compile
- [x] dbt run –full-refresh
- [x] dbt run
- [x] dbt test
- [ ] dbt run –vars (if applicable)

Before marking this PR as "ready for review" the following have been applied:
- [x] The appropriate issue has been linked and tagged
- [x] You are assigned to the corresponding issue and this PR
- [x] BuildKite integration tests are passing

### Detailed Validation
Please acknowledge that the following validation checks have been performed prior to marking this PR as "ready for review":
- [x] You have validated these changes and assure this PR will address the respective Issue/Feature.
- [x] You are reasonably confident these changes will not impact any other components of this package or any dependent packages.
- [x] You have provided details below around the validation steps performed to gain confidence in these changes.

see hex linked in height

### Standard Updates
Please acknowledge that your PR contains the following standard updates:
- Package versioning has been appropriately indexed in the following locations:
    - [x] indexed within dbt_project.yml
    - [x] indexed within integration_tests/dbt_project.yml
- [x] CHANGELOG has individual entries for each respective change in this PR
    
- [x] README updates have been applied (if applicable)
    
- [ ] DECISIONLOG updates have been updated (if applicable)
- [x] Appropriate yml documentation has been added (if applicable)

### dbt Docs
Please acknowledge that after the above were all completed the below were applied to your branch:
- [x] docs were regenerated (unless this PR does not include any code or yml updates)

### If you had to summarize this PR in an emoji, which would it be?
 
🍳

2024-02-29 21:08 UTC, fivetran-joemarkiewicz approved these changes
LGTM

2024-02-29 21:08 UTC, fivetran-joemarkiewicz commented on packages.yml
> +  warn-unpinned: false
Reminder to swap before release

2024-02-29 23:15 UTC, fivetran-catfritz requested changes
One small change and a question!

2024-02-29 23:15 UTC, fivetran-catfritz commented on CHANGELOG.md
> +# dbt_marketo_source v0.11.0
typo 😺
```suggestion
# dbt_marketo v0.11.0
```

2024-02-29 23:15 UTC, fivetran-catfritz commented on CHANGELOG.md
> +- Ensures that `stg_marketo__lead` (and therefore `marketo__leads`) has and documents the below columns, all [standard](https://developers.marketo.com/rest-api/lead-database/fields/list-of-standard-f
I'm wondering does this bit:
>   - `unsubscribed` -> aliased as `is_unsubscribed` (🚨 breaking change 🚨)
>   - `email_invalid` -> aliased as `is_email_invalid` (🚨 breaking change 🚨)

make this bit not be entirely true?:
> If your `LEAD` table contains the following fields, nothing will change for you.

Would their columns get renamed?

2024-02-29 23:15 UTC, fivetran-catfritz commented on README.md
> +<details open><summary>Expand/Collapse details</summary>
Ohh this is cool!

2024-03-06 18:29 UTC, fivetran-catfritz approved these changes
lgtm for batching with the next update!

2024-03-20 18:06 UTC, merged